### ISSUE TITLE
OpenShift - Scaling up the nodes

### ISSUE THREAD

**Issue by daniyalj** [jfrog/artifactory-docker-examples#130]
:wave:

I have successfully installed Artifactory running on OpenShift using the templates and have a primary and secondary node running. My question is, how do I scale up if I want to add a third node to the cluster?

**Comment by elioengcomp** [comment]
Hi @daniyalj ,

Thanks for your message.

Right now there is no scaling options in the current version of the templates. The shorter route to add a third node would be just copying the template files related to the secondary node, renaming them to avoid naming conflicts and adding them to the helper scripts.

The longer and more elegant route would be modifying the templates and adding support to Stateful Sets to the secondary nodes, so you could scale the number of secondary replicas up and down. The reason why we do not have support for Stateful Sets is because it was not supported by Openshift at the time we created the templates.

**Comment by daniyalj** [comment]
Hi @elioengcomp would renaming and adding a third deployment config for an additional node be supported under the Enterprise license?

**Comment by daniyalj** [comment]
Perfect thank you!

**Comment by elioengcomp** [comment]
You are welcome! ;)
