### ISSUE TITLE
Production Support

### ISSUE THREAD

**Issue by SterlingSC86** [jfrog/artifactory-docker-examples#176]
Hi guys,

In the documentation for the docker-compose examples you specifically say:
IMPORTANT: The files under the files directory included in this repository are for example purposes only and should NOT be used for any production deployments!

Are you able to provide more info here? Is it just the self-signed certificates or are there ther concerns using this example to run Artifactory?

**Comment by eldada** [comment]
Hi @SterlingSC86. The purpose of this repository is to provide easy templates and examples of running Artifactory in various Docker setups. Standalone Docker and Docker compose.
The provided `files` directory has some resources used to make the examples work out of the box. But - since they have SSL/TLS keys, you should not use these files in any production env and replace them with your own.
Only the access key + certificate and nginx TLS key and certificate are considered the sensitive files and should be replaced by your own set of files.
In general - this repository is examples only, and used by [JFrog's official Artifactory docs](https://www.jfrog.com/confluence/display/RTF/Installing+with+Docker) for reference.

I hope this provides the answers you wanted.

**Comment by SterlingSC86** [comment]
Thanks for the reply! Thats great!
