### ISSUE TITLE
Running Artifactory and Postgres as non-root

### ISSUE THREAD

**Issue by hr1sh1kesh** [jfrog/artifactory-docker-examples#78]
Hello, 
     I am trying to deploy Artifactory (Pro in a weeks time) OSS. I need to deploy Artifactory and Postgres with a non-root user. Just wondering if you have baked images which would allow that or would i need to write a dockerfile on my own. My environment doesn't allow running privileged containers. (kubernetes 1.8)

I did see a different issue where the security context was set to 1030 user id to run but caused issues since currently Artifactory doesn't allow to run as non-root Has that been fixed so that i can try it out?

**Comment by eldada** [comment]
Hi @hr1sh1kesh.
We have support for pure non-root for `Artifactory` coming soon. As for `Postgresql`, since we use an external Docker image, we have no control over this. See https://github.com/docker-library/postgres. All versions still use **root** to execute the entrypoint and then start **postgres** with **gosu**.

**Comment by eldada** [comment]
Hi @hr1sh1kesh. Recent Artifactory versions already support pure non-root. You can see our [official helm charts](https://github.com/jfrog/charts) to see how it's used.
As for PostgreSQL, we still use an image/chart that does not support pure non-root. You can install the database yourself and pass it to Artifactory. See the documentation on how to set an external database.
